---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: expense-app
  name: expense-app
spec:
  replicas: 
  selector:
    matchLabels:
      app: expense-app
  template:
    metadata:
      labels:
        app: expense-app
    spec:
      containers:
      - name: expense-app
        image: 192.168.116.28:5000/expense-app:v1
        imagePullPolicy: Always
        volumeMounts:
        - name: ballerina-config
          mountPath: "/home/ballerina/service-exp-claim/config"
          readOnly: false
      volumes:
      - name: ballerina-config
        secret:
         secretName: ballerina-config

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: expense-app
  name: expense-app
spec:
  ports:
  - nodePort: 32071
    port: 37071
    protocol: TCP
    targetPort: 37071
  selector:
    app: expense-app
  type: NodePort